version: "3"

services:
  wordpress:
    image: wordpress:latest
    depends_on: 
      - wordpress-db
    # ports でポートフォワーディングを指定.
    ports:
      - "8888:80"
    # links で連携させるコンテナを示す
    links:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: database_password

  wordpress-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    # mysqlのようにenvironmentで指定が必須なやつもある
    environment: 
      MYSQL_ROOT_PASSWORD: database_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: database_password